import 'package:estin_losts/shared/models/post.dart';

final postsEamples = <Post>[
  Post(
    id: '1',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Lost phone',
    description: 'I lost my phone in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "Amman, Jordan",
    type: PostType.lost,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: <PostImage>[
      PostImage(
        id: '1',
        name: "image1",
        fileStorageFolder: "posts",
        postID: "1",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '2',
        name: "image2",
        fileStorageFolder: "posts",
        postID: "1",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '3',
        name: "image3",
        fileStorageFolder: "posts",
        postID: "1",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '2',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Lost wallet',
    description: 'I lost my wallet in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "Amman, Jordan",
    type: PostType.lost,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '4',
        name: "image4",
        fileStorageFolder: "posts",
        postID: "2",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '5',
        name: "image5",
        fileStorageFolder: "posts",
        postID: "2",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '6',
        name: "image6",
        fileStorageFolder: "posts",
        postID: "2",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '3',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Lost keys',
    description: 'I lost my keys in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "Amman, Jordan",
    type: PostType.lost,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '7',
        name: "image7",
        fileStorageFolder: "posts",
        postID: "3",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '8',
        name: "image8",
        fileStorageFolder: "posts",
        postID: "3",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '9',
        name: "image9",
        fileStorageFolder: "posts",
        postID: "3",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '4',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Lost bag',
    description: 'I lost my bag in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "Beside the fountain",
    type: PostType.lost,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '10',
        name: "image10",
        fileStorageFolder: "posts",
        postID: "4",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '11',
        name: "image11",
        fileStorageFolder: "posts",
        postID: "4",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '12',
        name: "image12",
        fileStorageFolder: "posts",
        postID: "4",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '5',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Lost glasses',
    description: 'I lost my glasses in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "Beside the fountain",
    type: PostType.lost,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '13',
        name: "image13",
        fileStorageFolder: "posts",
        postID: "5",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '14',
        name: "image14",
        fileStorageFolder: "posts",
        postID: "5",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '15',
        name: "image15",
        fileStorageFolder: "posts",
        postID: "5",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  // do no 5 fouds examples
  Post(
    id: '6',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Found phone',
    description: 'I found a phone in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "In the left corner",
    type: PostType.found,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '16',
        name: "image16",
        fileStorageFolder: "posts",
        postID: "6",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '17',
        name: "image17",
        fileStorageFolder: "posts",
        postID: "6",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '18',
        name: "image18",
        fileStorageFolder: "posts",
        postID: "6",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '7',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Found wallet',
    description: 'I found a wallet in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "In the right corner of the park",
    type: PostType.found,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '19',
        name: "image19",
        fileStorageFolder: "posts",
        postID: "7",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '20',
        name: "image20",
        fileStorageFolder: "posts",
        postID: "7",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '21',
        name: "image21",
        fileStorageFolder: "posts",
        postID: "7",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '8',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Found keys',
    description: 'I found keys in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "In the middle of the park",
    type: PostType.found,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '22',
        name: "image22",
        fileStorageFolder: "posts",
        postID: "8",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '23',
        name: "image23",
        fileStorageFolder: "posts",
        postID: "8",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '24',
        name: "image24",
        fileStorageFolder: "posts",
        postID: "8",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '9',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Found bag',
    description: 'I found a bag in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "In the middle of the park",
    type: PostType.found,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '25',
        name: "image25",
        fileStorageFolder: "posts",
        postID: "9",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '26',
        name: "image26",
        fileStorageFolder: "posts",
        postID: "9",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '27',
        name: "image27",
        fileStorageFolder: "posts",
        postID: "9",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
  Post(
    id: '10',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    title: 'Found glasses',
    description: 'I found glasses in the park',
    locationLatitude: 31.963158,
    locationLongitude: 35.930359,
    locationDescription: "In the middle of the park",
    type: PostType.found,
    hasBeenFound: false,
    hasBeenDelivered: false,
    claimedByUser: false,
    foundByUser: false,
    userID: '1',
    user: null,
    images: [
      PostImage(
        id: '28',
        name: "image28",
        fileStorageFolder: "posts",
        postID: "10",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '29',
        name: "image29",
        fileStorageFolder: "posts",
        postID: "10",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      ),
      PostImage(
        id: '30',
        name: "image30",
        fileStorageFolder: "posts",
        postID: "10",
        url: 'https://images.unsplash.com/photo-1612838320302-4b3b3b3b3b3b',
      )
    ],
    claimersCount: 0,
    claimers: [],
    foundersCount: 0,
    founders: [],
  ),
];

const postImageURL = "https://www.luxuryformen.com/media/catalog/category/Note_books-notitieboeken.jpg";